---

# Generate config files in the host
- name: create zookeeper config directory
  file:
    path: "{{ zookeeper_config_dir }}"
    state: directory
    follow: yes
    mode: 0755
  sudo: yes
  tags:
    - zookeeper

- name: Create zookeeper config file
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_config_dir }}/zoo.cfg"
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Create zookeeper environments file
  template:
    src: environment.j2
    dest: "{{ zookeeper_config_dir }}/environment"
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Create zookeeper configuration.xsl file
  template:
    src: configuration.xsl.j2
    dest: "{{ zookeeper_config_dir }}/configuration.xsl"
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Create zookeeper myid file
  copy:
    content: "{{ zookeeper_id }}"
    dest: "{{ zookeeper_config_dir }}/myid"
    mode: 0644
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Create zookeeper log4j file
  template:
    src: log4j.properties.j2
    dest: "{{ zookeeper_config_dir }}/log4j.properties"
  sudo: yes
  notify:
    - restart zookeeper
  tags:
    - zookeeper

- name: Set Zookeeper consul service definition
  sudo: yes
  template:
    src: zookeeper-consul.j2
    dest: "{{ consul_dir }}/zookeeper.json"
  tags:
    - zookeeper
    
- name: remove zookeeper.override
  file:
    path: "/etc/init/zookeeper.override"
    state: absent
  sudo: yes
  tags:
    - zookeeper

- name: ensure zookeeper is running (and enable it at boot)
  sudo: yes
  service:
    name: zookeeper
    state: restarted
    enabled: yes
  tags:
    - zookeeper

