#- name: install wait script
#  sudo: yes
#  template:
#    src: marathon-wait-for-listen.sh.j2
#    dest: /usr/local/bin/marathon-wait-for-listen.sh
#    mode: 0755
#  tags:
#    - marathon

- name: create marathon conf directory
  when: marathon_conf_dir is defined
  file:
    path: "{{ marathon_conf_dir }}"
    state: directory
    mode: 0755
  sudo: yes
  tags:
    - marathon

- name: remove loopback ip 
  lineinfile: 
    dest: "/etc/hosts"
    regexp: "^127.0.1.1"
    state: absent

- name: Create ips file
  copy:
    content: "{{ ansible_eth0.ipv4.address }}"
    dest: "{{ marathon_conf_dir }}/hostname"
    mode: 0644
  sudo: yes
  tags:
    - marathon
    
- name: Create marathon zookeeper addresses file 1
  copy:
    content: "zk://{{ zookeeper_peers_nodes }}/mesos"
    dest: "{{ marathon_conf_dir }}/master"
    mode: 0644
  sudo: yes
  tags:
    - marathon
    
- name: Create marathon zookeeper addresses file 2
  copy:
    content: "zk://{{ zookeeper_peers_nodes }}/marathon"
    dest: "{{ marathon_conf_dir }}/zk"
    mode: 0644
  sudo: yes
  tags:
    - marathon

- name: restart marathon
  sudo: yes
  service:
    name: marathon
    state: restarted
    enabled: yes
  tags:
    - marathon

- name: Set marathon consul service definition
  sudo: yes
  template:
    src: marathon-consul.j2
    dest: "{{ marathon_consul_dir }}/marathon.json"
  notify:
    - restart consul
