---  
- name: Enable init script
  replace: 
    dest: "/etc/default/haproxy"
    regexp: "ENABLED=0"
    replace: "ENABLED=1"
    
- name: configure HAProxy conf
  sudo: yes
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0755
    
- name: start haproxy
  sudo: yes
  service:
    name: haproxy
    state: restarted
    enabled: yes
    
- name: wait for haproxy
  wait_for:
    host: "0.0.0.0"
    port: 9090
    delay: 10
    
- name: configure bamboo conf
  sudo: yes
  template:
    src: production.json.j2
    dest: /var/bamboo/production.json
    owner: root
    group: root
    mode: 0755
    
- name: configure bamboo haproxy conf
  sudo: yes
  copy:
    src: haproxy_template.cfg
    dest: /var/bamboo/haproxy_template.cfg
    owner: root
    group: root
    mode: 0755
    
- name: start bamboo-server
  sudo: yes
  service:
    name: bamboo-server
    state: started
    enabled: yes

- name: Set haproxy consul service definition
  sudo: yes
  template:
    src: haproxy-consul.j2
    dest: "/etc/consul.d/haproxy.json"
