---
# Tasks for Master nodes
- name: set mesos-master consul service definition
  when: mesos_install_mode == "master"
  sudo: yes
  template:
    src: mesos-master-consul.j2
    dest: "{{ consul_dir }}/mesos-master.json"
  notify:
    - restart consul
  tags:
    - mesos-master

- name: create mesos-master work directory
  when: mesos_install_mode == "master"
  file:
    path: "{{ mesos_master_work_dir }}"
    state: directory
    mode: 0755
  sudo: yes
  tags:
    - mesos-master
    
- name: Create mesos zookeeper addresses file
  when: mesos_install_mode == "master"
  copy:
    content: "zk://{{ zookeeper_peers_nodes }}/mesos"
    dest: "/etc/mesos/zk"
    mode: 0644
  sudo: yes
  tags:
    - mesos-master
    
- name: Create ips file
  when: mesos_install_mode == "master"
  copy:
    content: "{{ ansible_eth0.ipv4.address }}"
    dest: "/etc/mesos-master/ip"
    mode: 0644
  sudo: yes
  tags:
    - mesos-master
    
- name: Create hosts file
  when: mesos_install_mode == "master"
  copy:
    content: "{{ ansible_eth0.ipv4.address }}"
    dest: "/etc/mesos-master/hostname"
    mode: 0644
  sudo: yes
  tags:
    - mesos-master
    
- name: Create mesos quorum file
  when: mesos_install_mode == "master"
  copy:
    content: "{{ mesos_quorum }}"
    dest: "/etc/mesos-master/quorum"
    mode: 0644
  sudo: yes
  tags:
    - mesos-master
    
- name: remove mesos-master.override
  when: mesos_install_mode == "master"
  file:
    path: "/etc/init/mesos-master.override"
    state: absent
  sudo: yes
  tags:
    - mesos-master
    
- name: stop mesos-slave service
  when: mesos_install_mode == "master"
  sudo: yes
  service:
    name: mesos-slave
    state: stopped
    enabled: no
  tags:
    - mesos-master
    
- name: remove mesos-slave service from startup
  when: mesos_install_mode == "master"
  sudo: yes
  command: "sudo update-rc.d -f mesos-slave remove"
  tags:
    - mesos-master

- name: restart mesos-master
  when: mesos_install_mode == "master"
  sudo: yes
  service:
    name: mesos-master
    state: restarted
    enabled: yes
  tags:
    - mesos-master
