---
- name: download mesos-dns package
  sudo: yes
  get_url:
    url: '{{ mesos_dns_download }}'
    dest: /usr/bin/{{ mesos_dns_filename }}
  tags:
    - mesos-dns
    
- name: change mesos-dns binary permissions
  sudo: yes
  file: 
    path: /usr/bin/{{ mesos_dns_filename }}
    owner: root
    group: root
    mode: 0755
  tags:
    - mesos-dns

- name: make config directory
  sudo: yes
  file:
    dest: /etc/mesos-dns
    state: directory
  tags:
    - mesos-dns

- name: configure mesos-dns
  sudo: yes
  template:
    src: config.json.j2
    dest: /etc/mesos-dns/config.json
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - mesos-dns
    
- name: configure mesos-dns upstart conf
  sudo: yes
  template:
    src: mesos-dns.conf.j2
    dest: /etc/init/mesos-dns.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - mesos-dns
    
- name: restart mesos-dns
  service:
    name: mesos-dns
    state: restarted
  sudo: yes
    
#- name: generate mesos-dns consul service
#  sudo: yes
#  copy:
#    src: 'mesos-dns-consul.json'
#    dest: '/etc/consul.d/mesos-dns.json'